name: FlagsH
version: ${version}
main: fr.formiko.flagsh.FlagsHPlugin
description: Display banners as flags
author: Hydrolien
website: https://github.com/HydrolienF/FlagsH
api-version: '1.20'
folia-supported: true